##### 9-1: ndarray Manipulation -1

In [65]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5)) # Sample - 10, feature 5

print(arr.shape)

(10, 5)


In [66]:
# Changing Shape

b = arr.reshape(5, 10) # All data must exists can't say (3, 2) on 50 items array 

print(b.shape)
print(b.ndim)
print(b)

(5, 10)
2
[[83 75 93 67 96 59 16 40 82 70]
 [10 60 89 16 17  1 81  7  3 11]
 [91 87 32 21 97 88  1 25  1 96]
 [82 83 29 86 30 52 97 81 59 68]
 [78 51 12 89 72 35 25 71 18 81]]


In [67]:
flatten = b.flatten() # to convert to 1d array

print(flatten)
print(flatten.ndim)

column_wise_flattening = np.ravel(b, order="F") # Column Wise
row_wise_flattening = np.ravel(b, order="C") # Column Wise

print(column_wise_flattening)
print(row_wise_flattening)

[83 75 93 67 96 59 16 40 82 70 10 60 89 16 17  1 81  7  3 11 91 87 32 21
 97 88  1 25  1 96 82 83 29 86 30 52 97 81 59 68 78 51 12 89 72 35 25 71
 18 81]
1
[83 10 91 82 78 75 60 87 83 51 93 89 32 29 12 67 16 21 86 89 96 17 97 30
 72 59  1 88 52 35 16 81  1 97 25 40  7 25 81 71 82  3  1 59 18 70 11 96
 68 81]
[83 75 93 67 96 59 16 40 82 70 10 60 89 16 17  1 81  7  3 11 91 87 32 21
 97 88  1 25  1 96 82 83 29 86 30 52 97 81 59 68 78 51 12 89 72 35 25 71
 18 81]


In [68]:
# Array Concatenation

a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print(a)
print(b)

# We want to merge two array and then train model
# Two ways: Row & Column wise
# Row wise concatenate: Column count should match
# Column wise concatenate: Row count should match

con_row_wise = np.concatenate((a, b), axis=0) # Row wise
con_col_wise = np.concatenate((a, b), axis=1) # Column wise

print(con_row_wise)
print(con_col_wise)

[[7 1 4]
 [9 1 2]]
[[26 29 20]
 [24 27 28]]
[[ 7  1  4]
 [ 9  1  2]
 [26 29 20]
 [24 27 28]]
[[ 7  1  4 26 29 20]
 [ 9  1  2 24 27 28]]


### 9-2: ndarray Manipulation - 2

In [69]:
# Transpose

mat = np.array([[10, 20, 30],
               [30, 40, 50]
               ])

transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [70]:
# Array Split

a = np.random.randint(1, 10, size=(10, ))

# Array Split -> Dynamically adjust items
splitted_array = np.array_split(a, 3)

print(a)
print(splitted_array)

# Split -> Equal Division
splitted_array = np.split(a, 3)

[9 5 6 8 5 6 9 1 6 6]
[array([9, 5, 6, 8], dtype=int32), array([5, 6, 9], dtype=int32), array([1, 6, 6], dtype=int32)]


ValueError: array split does not result in an equal division

### 9-3: ndarray Arithmetic Operators and Mathematical function

In [72]:
# Faster for vectorization

x = np.array([10, 8, 20, 30, 40, 100])
y = np.array([2, 3, 4, 5])

add = x + y # Addition
add_2 = np.add(x, y)
print(add)
print(add_2)
# In tradition list we can't do this instead it will add items

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x / y
print(div)

remainder = x % y
print(remainder)

# Also np.subtract(), multiply(), divide(), remainder()



ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [ ]:
# Mathematical Function

x = np.array([10, 8, 20, 30, 16, 40, 100])

# Trigonometry
# sin, cos, tan values in radian
sin_val = np.sin(x) 
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

tan_val = np.tan(x)
print(tan_val)

# Degree: D * PI / 180
# Radian: R * 180 / PI
deg_con = np.rad2deg(x)
print(deg_con)

ran_con = np.deg2rad(deg_con)
print(deg_con)

# Log

base_10_log_val = np.log10(x)
print(base_10_log_val)

base_2_log_val = np.log2(x)
print(base_2_log_val)

# Square Root

sqrt = np.sqrt(x)

print(sqrt)

[-0.54402111  0.98935825  0.91294525 -0.98803162 -0.28790332  0.74511316
 -0.50636564]
[-0.83907153 -0.14550003  0.40808206  0.15425145 -0.95765948 -0.66693806
  0.86231887]
[ 0.64836083 -6.79971146  2.23716094 -6.4053312   0.30063224 -1.11721493
 -0.58721392]
[ 572.95779513  458.3662361  1145.91559026 1718.87338539  916.73247221
 2291.83118052 5729.57795131]
[ 572.95779513  458.3662361  1145.91559026 1718.87338539  916.73247221
 2291.83118052 5729.57795131]
[1.         0.90308999 1.30103    1.47712125 1.20411998 1.60205999
 2.        ]
[3.32192809 3.         4.32192809 4.9068906  4.         5.32192809
 6.64385619]
[ 3.16227766  2.82842712  4.47213595  5.47722558  4.          6.32455532
 10.        ]


In [ ]:
# Different

s = np.sum(x)
print(s)

# Prefix sum
cuml = np.cumulative_sum(x)
print(cuml)

224
[ 10  18  38  68  84 124 224]
