##### 9-1: ndarray Manipulation -1

In [1]:
import numpy as np

arr = np.random.randint(1, 100, size=(10, 5)) # Sample - 10, feature 5

print(arr.shape)

(10, 5)


In [2]:
# Changing Shape

b = arr.reshape(5, 10) # All data must exists can't say (3, 2) on 50 items array 

print(b.shape)
print(b.ndim)
print(b)

(5, 10)
2
[[78 91 45 85 32 28  9 64 83 82]
 [19 98 55 42 85 35 65 66 99 70]
 [72 84 18 77 19 31 52 95 54 78]
 [73 37 80 49 85 80 55  6 42 81]
 [66 76 31 65 57 98 67  8 50 25]]


In [3]:
flatten = b.flatten() # to convert to 1d array

print(flatten)
print(flatten.ndim)

column_wise_flattening = np.ravel(b, order="F") # Column Wise
row_wise_flattening = np.ravel(b, order="C") # Column Wise

print(column_wise_flattening)
print(row_wise_flattening)

[78 91 45 85 32 28  9 64 83 82 19 98 55 42 85 35 65 66 99 70 72 84 18 77
 19 31 52 95 54 78 73 37 80 49 85 80 55  6 42 81 66 76 31 65 57 98 67  8
 50 25]
1
[78 19 72 73 66 91 98 84 37 76 45 55 18 80 31 85 42 77 49 65 32 85 19 85
 57 28 35 31 80 98  9 65 52 55 67 64 66 95  6  8 83 99 54 42 50 82 70 78
 81 25]
[78 91 45 85 32 28  9 64 83 82 19 98 55 42 85 35 65 66 99 70 72 84 18 77
 19 31 52 95 54 78 73 37 80 49 85 80 55  6 42 81 66 76 31 65 57 98 67  8
 50 25]


In [4]:
# Array Concatenation

a = np.random.randint(1, 10, size=(2, 3))
b = np.random.randint(20, 30, size=(2, 3))

print(a)
print(b)

# We want to merge two array and then train model
# Two ways: Row & Column wise
# Row wise concatenate: Column count should match
# Column wise concatenate: Row count should match

con_row_wise = np.concatenate((a, b), axis=0) # Row wise
con_col_wise = np.concatenate((a, b), axis=1) # Column wise

print(con_row_wise)
print(con_col_wise)

[[6 1 8]
 [6 6 4]]
[[29 28 27]
 [27 28 21]]
[[ 6  1  8]
 [ 6  6  4]
 [29 28 27]
 [27 28 21]]
[[ 6  1  8 29 28 27]
 [ 6  6  4 27 28 21]]


### 9-2: ndarray Manipulation - 2

In [5]:
# Transpose

mat = np.array([[10, 20, 30],
               [30, 40, 50]
               ])

transpose = mat.T

print(transpose)

[[10 30]
 [20 40]
 [30 50]]


In [6]:
# Array Split

a = np.random.randint(1, 10, size=(10, ))

# Array Split -> Dynamically adjust items
splitted_array = np.array_split(a, 3)

print(a)
print(splitted_array)

# Split -> Equal Division
splitted_array = np.split(a, 3)

[6 2 9 6 7 3 8 7 7 6]
[array([6, 2, 9, 6]), array([7, 3, 8]), array([7, 7, 6])]


ValueError: array split does not result in an equal division

### 9-3: ndarray Arithmetic Operators and Mathematical function

In [ ]:
# Faster for vectorization

x = np.array([10, 8, 20, 30, 40, 100])
y = np.array([2, 3, 4, 5])

add = x + y # Addition
add_2 = np.add(x, y)
print(add)
print(add_2)
# In tradition list we can't do this instead it will add items

sub = x - y
print(sub)

mul = x * y
print(mul)

div = x / y
print(div)

remainder = x % y
print(remainder)

# Also np.subtract(), multiply(), divide(), remainder()



ValueError: operands could not be broadcast together with shapes (6,) (4,) 

In [ ]:
# Mathematical Function

x = np.array([10, 8, 20, 30, 16, 40, 100])

# Trigonometry
# sin, cos, tan values in radian
sin_val = np.sin(x) 
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

tan_val = np.tan(x)
print(tan_val)

# Degree: D * PI / 180
# Radian: R * 180 / PI
deg_con = np.rad2deg(x)
print(deg_con)

ran_con = np.deg2rad(deg_con)
print(deg_con)

# Log

base_10_log_val = np.log10(x)
print(base_10_log_val)

base_2_log_val = np.log2(x)
print(base_2_log_val)

# Square Root

sqrt = np.sqrt(x)

print(sqrt)

[-0.54402111  0.98935825  0.91294525 -0.98803162 -0.28790332  0.74511316
 -0.50636564]
[-0.83907153 -0.14550003  0.40808206  0.15425145 -0.95765948 -0.66693806
  0.86231887]
[ 0.64836083 -6.79971146  2.23716094 -6.4053312   0.30063224 -1.11721493
 -0.58721392]
[ 572.95779513  458.3662361  1145.91559026 1718.87338539  916.73247221
 2291.83118052 5729.57795131]
[ 572.95779513  458.3662361  1145.91559026 1718.87338539  916.73247221
 2291.83118052 5729.57795131]
[1.         0.90308999 1.30103    1.47712125 1.20411998 1.60205999
 2.        ]
[3.32192809 3.         4.32192809 4.9068906  4.         5.32192809
 6.64385619]
[ 3.16227766  2.82842712  4.47213595  5.47722558  4.          6.32455532
 10.        ]


In [ ]:
# Different

s = np.sum(x)
print(s)

# Prefix sum
cuml = np.cumulative_sum(x)
print(cuml)

224
[ 10  18  38  68  84 124 224]


### 9-4: Numpy Logical Functions

In [11]:
# Comparison - >, <, >=, <=, ==, !=

x = np.array([10, 8, 16, 100])
y = np.array([2, 3, 4, 5])

greater_than = x > y
print(greater_than)

less_than = x < y
print(less_than)

equal = x == y
print(equal)

# all () -> shob true kina
# any () -> jekunu ekta true ase kina

print(np.all(greater_than))
print(np.any(equal))

[ True  True  True  True]
[False False False False]
[False False False False]
True
False


### 9-5: ndarray Sorting

In [13]:
# Inplace
# 1d array
x = np.array([10, 8, 16, 100])

z = x.copy()

print(z)

z.sort()

print(z)


[ 10   8  16 100]
[  8  10  16 100]


In [17]:
# Copy sorting

print(x)
sort_arr = np.sort(x)

print(sort_arr)
print(x)

[ 10   8  16 100]
[  8  10  16 100]
[ 10   8  16 100]


In [18]:
# 2d array sorting

mat = np.array([[10, 3, 5],
                [8, 4, 9]])

# Horizon axis = 1
hor_sort = np.sort(mat, axis=1)

# Vertical axis = 0
ver_sort = np.sort(mat, axis=0)

print(hor_sort)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


### 9-6: ndarray Searching

In [ ]:
print(x)

# np.where()

index = np.where(x==8) # returns index

print(index)

index = np.where(x>8) # returns index

print(index)

index = np.where(x>8, x, 0) # Find and modify, returns array

print(index)
 

[ 10   8  16 100]
(array([1]),)
[ 10   0  16 100]


In [33]:
print(mat)

index = np.where(mat > 8) # return index

print(index)

index = np.where(mat > 8, mat, 0) # return array

print(index)

[[10  3  5]
 [ 8  4  9]]
(array([0, 1]), array([0, 2]))
[[10  0  0]
 [ 0  0  9]]


In [ ]:
print(x)
maximum_value = np.argmax(x) # Tells the index

# Use max() method to get the number

print(maximum_value)

minmam_value = np.argmin(x) # Tells the index

print(minmam_value)

[ 10   8  16 100]
3
1


#### 9-7: ndarray Counting

In [44]:
a = np.random.randint(1, 100, size=(100,))

print(a)

[17 82 99 31  8 50 96 62 38  2 71 17 91 33 98 42 88 56 41 76 38 48 88 98
 13 93 55 86  5 99 14 76 44 44 61 16 28 58 70 43 52 13 98  2 54 34 39 82
 68 26 27  7 64 11 18 82 13 93 27 33 10  7 59 76 45 32 17 45 80 12 58 15
 71 74 63  4 74 42 94 88 87 96 79  6 41 61 96 86 85 94 66 21 10 83 98 69
 87 64 66 86]


In [59]:
value_greater_than_60 = np.count_nonzero(a>40)
# Can use any conditiond array it will return indexes as array inside tuple as indexes

print(value_greater_than_60)

65


In [58]:
unique_value, count = np.unique(a, return_counts=True)
unique_value_count = np.unique_counts(a)

print(unique_value)
print(count)
print(unique_value_count.counts)

[ 2  4  5  6  7  8 10 11 12 13 14 15 16 17 18 21 26 27 28 31 32 33 34 38
 39 41 42 43 44 45 48 50 52 54 55 56 58 59 61 62 63 64 66 68 69 70 71 74
 76 79 80 82 83 85 86 87 88 91 93 94 96 98 99]
[2 1 1 1 2 1 2 1 1 3 1 1 1 3 1 1 1 2 1 1 1 2 1 2 1 2 2 1 2 2 1 1 1 1 1 1 2
 1 2 1 1 2 2 1 1 1 2 2 3 1 1 3 1 1 3 2 3 1 2 2 3 4 2]
[2 1 1 1 2 1 2 1 1 3 1 1 1 3 1 1 1 2 1 1 1 2 1 2 1 2 2 1 2 2 1 1 1 1 1 1 2
 1 2 1 1 2 2 1 1 1 2 2 3 1 1 3 1 1 3 2 3 1 2 2 3 4 2]


### 9-8: Statistical function

In [ ]:
# Data load

data = np.genfromtxt("./student_scores.csv", delimiter=',', skip_header=True)

print(data)


[[78. 85. 82.]
 [56. 67. 72.]
 [89. 92. 88.]
 [45. 52. 58.]
 [70. 75. 80.]
 [92. 90. 91.]
 [61. 60. 62.]
 [55. 57. 54.]
 [88. 89. 87.]
 [74. 70. 76.]
 [66. 69. 68.]
 [80. 82. 81.]
 [59. 64. 60.]
 [73. 78. 74.]
 [91. 93. 90.]
 [68. 71. 69.]
 [77. 79. 78.]
 [84. 86. 85.]
 [62. 63. 65.]
 [95. 97. 96.]]


In [105]:

# Maximum Math Column Marks
math_marks = data[::,:1]
# data[row_start:row_end,column_start:column_end:slice_step]

print(math_marks.T)

max_math_marks = np.max(math_marks) # Maximum

print(max_math_marks)

min_math_marks = np.min(math_marks) # Minimum

print(min_math_marks)

mean_math_marks = np.mean(math_marks) # Average

print(mean_math_marks)

median_math_marks = np.median(math_marks) # Moddok

print(median_math_marks)

# Standard Deviation
# The values of how much is scattered or diverse or how much near to that value
# The higher the value the higher the data is scattered

std_math_marks = np.std(math_marks)

print(std_math_marks)


[[78. 56. 89. 45. 70. 92. 61. 55. 88. 74. 66. 80. 59. 73. 91. 68. 77. 84.
  62. 95.]]
95.0
45.0
73.15
73.5
13.788672887555204


### 9-9: Linear Algebra with NumPy

In [ ]:
study_hours = np.array([2, 4, 5, 7, 8])
exam_scores = np.array([65, 75, 78, 88, 92])

data = np.array([study_hours, exam_scores])

In [ ]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([
    [7, 8],
    [9, 10],
    [11, 12]
])

# For dot product A row and B column count much match
dot_product = np.dot(A, B)

print(dot_product)

# Trace
print(np.trace(B))


[[ 58  64]
 [139 154]]
17


In [ ]:
# Determinant

sq_mat = np.array([[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]])

print(sq_mat.shape)

det_of_sq = np.linalg.det(sq_mat)

print(det_of_sq)

# Rank
rank_sq = np.linalg.matrix_rank(sq_mat)

print(rank_sq)

(3, 3)
6.66133814775094e-16
2


2
