### Problem 1

In [ ]:
import numpy as np

arr_1d = np.random.randint(1, 10, size=(10))
arr_2d = np.random.randint(1, 10, size=(10)).reshape(2, 5)
arr_3d = np.random.randint(1, 10, size=(9)).reshape(3, 3) 

man_arr_1d = np.array([1, 2, 3, 4, 5])
man_arr_2d = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
man_arr_3d = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]    
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ],
    [
        [13, 14, 15],
        [16, 17, 18]
    ]
])

print(arr_1d)
print(arr_2d)
print(arr_3d)

1
[8 5 1 7 8 7 6 9 9 8]
[[1 3 1 6 8]
 [2 5 1 9 5]]
[[6 8 9]
 [7 9 4]
 [4 3 5]]


### Problem 2

In [9]:
arr_1 = np.random.randint(0, 1, size=(3, 3))
arr_2 = np.random.randint(0, 10, size=(2, 5))
arr_3 = np.random.randint(7, 8, size=(3, 3))

print(arr_1)
print(arr_2)
print(arr_3)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[2 2 4 4 5]
 [1 2 3 8 7]]
[[7 7 7]
 [7 7 7]
 [7 7 7]]


### Problem 3

In [16]:
arr = np.arange(11, 51, 2)

print(arr)

[11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49]


### Problem 4

In [45]:
arr = np.random.randint(0, 15, size=(4, 4))

row = arr[0:1:,0:]
column = arr[::,3:]
sub_array = arr[1:3,1:3]

print(arr, end="\n\n")
print(row)
print(column)
print(sub_array)

[[ 8  6  1 11]
 [ 2  9  9  1]
 [ 1  1 12  0]
 [ 6  0  2 12]]

[[ 8  6  1 11]]
[[11]
 [ 1]
 [ 0]
 [12]]
[[ 9  9]
 [ 1 12]]
