### Problem 1

In [5]:
import numpy as np

arr_1d = np.random.randint(1, 10, size=(10))
arr_2d = np.random.randint(1, 10, size=(10)).reshape(2, 5)
arr_3d = np.random.randint(1, 10, size=(9)).reshape(3, 3) 

print(arr_1d)
print(arr_2d)
print(arr_3d)

[9 4 8 5 8 3 4 6 4 4]
[[9 1 7 8 3]
 [5 6 2 4 7]]
[[3 3 3]
 [7 2 2]
 [9 6 9]]


### Problem 2

### Problem 3